site_name: sxs

repo_url: https://github.com/sxs-collaboration/sxs

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: true

nav:
  - Home: "index.md"
  - Tutorials:
    - "tutorials/00-Introduction.ipynb"
    - "tutorials/01-Simulations_and_Metadata.ipynb"
    - "tutorials/02-Simulation.ipynb"
    - "tutorials/03-Horizons.ipynb"
    - "tutorials/04-Waveforms.ipynb"
    - "tutorials/05-PreprocessingForFFTs.ipynb"
  - API:
    - "Load": "api/load.md"
    - "Simulations": "api/simulations.md"
    - "Simulation": "api/simulation.md"
    - "Metadata": "api/metadata.md"
    - "Time Series": "api/time_series.md"
    - "Horizons": "api/horizons.md"
    - "Waveforms": "api/waveforms.md"
  - "Calling from Mathematica": "mathematica.md"
  - "Calling from Julia": "julia.md"

theme:
  name: "material" # "readthedocs", "mkdocs", "material"
  #custom_dir: "docs/html"
  highlightjs: true
  hljs_languages:
    - python
    - julia
    - mathematica
  palette:
    scheme: sxs
  favicon: images/favicon.ico
  icon:
    logo: material/library
    #logo: images/sxs_logo.png
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
    # - toc.integrate 

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
